### **Using Numpy**

In [11]:
import numpy as np

# Step 1: Define the two vectors (|ψ₁⟩ and |ψ₂⟩)
psi_1 = np.array([1, 0])  # |0⟩
psi_2 = np.array([0, 1])  # |1⟩

# Tensor product |ψ₁⟩ ⊗ |ψ₂⟩
psi_tensor = np.kron(psi_1, psi_2)
print("Tensor product of |ψ₁⟩ and |ψ₂⟩:")
print(psi_tensor)

Tensor product of |ψ₁⟩ and |ψ₂⟩:
[0 1 0 0]


In [ ]:
# Step 2: Define the CNOT operator
CNOT = np.array([[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 0, 1],
                 [0, 0, 1, 0]])

In [12]:
# Step 3: Apply the CNOT operator on the tensor product state
new_state = np.dot(CNOT, psi_tensor)
print("\nState after applying CNOT operator:")
print(new_state)


State after applying CNOT operator:
[0 1 0 0]


In [13]:
# Step 4: Partial measurement of the first qubit
# Projection operator for measuring first qubit in |0⟩
P0 = np.array([[1, 0],
               [0, 0]])

In [14]:
# Extending this to a 4x4 matrix that acts on the full system
P0_full = np.kron(P0, np.eye(2))

In [15]:
# Apply the projection to get the post-measurement state
post_measurement_state = np.dot(P0_full, new_state)


In [16]:
# Normalize the post-measurement state
norm = np.linalg.norm(post_measurement_state)
if norm != 0:
    post_measurement_state /= norm

print("\nState after partial measurement (first qubit measured in |0⟩):")
print(post_measurement_state)


State after partial measurement (first qubit measured in |0⟩):
[0. 1. 0. 0.]


### **Using Qiskit**

In [8]:
from qiskit import QuantumCircuit
from qiskit.visualization import plot_histogram
from qiskit.quantum_info import Statevector

In [4]:
# Step 1: Initialize the Quantum Circuit with 2 qubits and 2 classical bits
qc = QuantumCircuit(2, 2)

# Initialize the first qubit |0> (already in this state) and the second qubit |1>
qc.x(1)  # Apply X-gate on the second qubit to set it to |1>

In [5]:
# Step 2: Apply the CNOT gate
# CNOT gate: control = qubit 0, target = qubit 1
qc.cx(0, 1)

# Visualize the circuit
print("Quantum Circuit:")
print(qc)

Quantum Circuit:
               
q_0: ───────■──
     ┌───┐┌─┴─┐
q_1: ┤ X ├┤ X ├
     └───┘└───┘
c: 2/══════════
               


In [6]:
# Step 3: Measure the qubits
qc.measure([0, 1], [0, 1])

In [9]:
backend = QasmSimulator()
backend_options = {"method": "statevector"}
 
# Circuit execution
job = execute(circuits, backend, backend_options=backend_options)
 
# Qobj execution
job = backend.run(qobj, backend_options=backend_options)

NameError: name 'QasmSimulator' is not defined

In [10]:
# Step 4: Simulate the circuit using the qasm simulator
simulator = Aer.get_backend('qasm_simulator')
job = QasmSimulator.run(qc, simulator, shots=1024)
result = job.result()

NameError: name 'Aer' is not defined

In [ ]:

# Get the counts (i.e., measurement outcomes)
counts = result.get_counts(qc)

# Plot the histogram of the outcomes
plot_histogram(counts)

# Display the quantum circuit diagram
qc.draw(output='mpl')

# Optional: View the statevector (before measurement)
state = Statevector.from_instruction(qc)
print("\nStatevector before measurement:")
print(state)